const PREFIX = 'native.calendar';

module.exports = {
  CHANGE_MONTH_LEFT_ARROW: `${PREFIX}.CHANGE_MONTH_LEFT_ARROW`,
  CHANGE_MONTH_RIGHT_ARROW: `${PREFIX}.CHANGE_MONTH_RIGHT_ARROW`,
  CHANGE_YEAR_LEFT_ARROW: `${PREFIX}.CHANGE_YEAR_LEFT_ARROW`,
  CHANGE_YEAR_RIGHT_ARROW: `${PREFIX}.CHANGE_YEAER_RIGHT_ARROW`,
  SELECT_DATE_SLOT: `${PREFIX}.SELECT_DATE_SLOT`,
  CALENDAR_HEADER_ARROW: `${PREFIX}.CALENDAR_HEADER_ARROW`,
};
